version: "3"

services:
    flask_user_dev:
        image: flask_user_dev:1.00
        container_name: flask_user_dev
        restart: unless-stopped
        command: manage.py runserver --host=0.0.0.0 --port=8080
        build:
            context: ../
            dockerfile: .dev-tools/Dockerfile
        ports:
            - "8080:8080"
        volumes:
            - ..:/usr/app